# Generated by Django 2.2.13 on 2020-06-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_name', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('metal_code', models.CharField(blank=True, max_length=3)),
                ('unit', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=25, null=True)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='api.Metal')),
            ],
        ),
    ]
